#!/usr/bin/env bash
# A Bash script that displays numbers from 1 to 100, FizzBuzz

i=1
while [ $i -le 100 ]
do
	if ! ((i % 15))
	then
		echo "FizzBuzz"
	elif ! ((i % 3))
	then
		echo "Fizz"
	elif ! ((i % 5))
	then
		echo "Buzz"
	else
		echo $i
	fi
	(( i++ ))
done
