#!/usr/bin/env bash
# A Bash script that displays the content of file /etc/passwd

filename='/etc/passwd'
while IFS=: read -r username password userid groupid comment homedir cmdshell
do
	echo "$username:$userid:$homedir"
done < $filename
