#!/usr/bin/env bash
# A Bash script that displays Holberton School 10 times, if statements

i=1
while [ $i -le 10 ]
do
	if [ $i = 9 ]
	then
		echo "Hi"
	else
		echo "Holberton School"
	fi
	(( i++ ))
done
